name: Deploy Python project to EC2

on:
  [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan 34.34.141.151 >> ~/.ssh/known_hosts

    - name: Execute deployment script via SSH
      run: | 
            ssh -i ~/.ssh/id_ed25519 ojojoe@34.34.141.151 
            bash /home/ojojoeyour-script.sh